<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DEEP" failures="1" tests="3" name="Test" time="78.596" errors="0" timestamp="2025-03-22T09:41:37 IST">
  <testcase classname="testCaseRepo.TC_001" name="LE_001" time="25.55">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCaseRepo.TC_001.LE_001(TC_001.java:23)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- LE_001 -->
  <testcase classname="testCaseRepo.TC_004" name="CON_001" time="40.587"/>
  <testcase classname="testCaseRepo.TC_002" name="LE_002" time="61.498"/>
  <testcase classname="genericUtility.BaseClass" name="@BeforeSuite dbConnection" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite dbConnection -->
  <testcase classname="genericUtility.BaseClass" name="@AfterSuite closeDBConnection" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite closeDBConnection -->
  <testcase classname="genericUtility.BaseClass" name="@BeforeSuite dbConnection" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite dbConnection -->
  <testcase classname="genericUtility.BaseClass" name="@AfterSuite closeDBConnection" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite closeDBConnection -->
</testsuite> <!-- Test -->
